---                                                                                                                            
driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept
verifier:
  name: inspec
platforms:
  - name: centos
    driver_config:
      platform: centos
      dockerfile: ./Dockerfile
suites:
  - name: default
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
